import os
import json
import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import get_linear_schedule_with_warmup

# We will treat this as a multi-label classification problem for the "symptoms" extraction, 
# or a simple sequence-to-sequence if we used T5. For simplicity and speed in this example, 
# we'll use DistilBERT to classify which symptoms are present.

class JSONLDataset(Dataset):
    def __init__(self, file_path, tokenizer, max_length=512):
        self.data = []
        self.tokenizer = tokenizer
        self.max_length = max_length
        
        # Load the JSONL generated by the Gemini script
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip(): continue
                record = json.loads(line)
                messages = record.get("messages", [])
                
                user_msg = next((m["content"] for m in messages if m["role"] == "user"), "")
                model_msg = next((m["content"] for m in messages if m["role"] == "model"), "{}")
                
                try:
                    parsed_output = json.loads(model_msg)
                    # For this simple local model, let's just train it to predict if "sciatica" or "lumbar" is in symptoms
                    symptoms = parsed_output.get("symptoms", [])
                    symptoms_lower = [s.lower() for s in symptoms]
                    
                    # Create some binary labels for common targets
                    has_sciatica = 1 if any('sciatica' in s for s in symptoms_lower) else 0
                    has_lumbar = 1 if any('lumbar' in s for s in symptoms_lower) else 0
                    has_radiculopathy = 1 if any('radiculopathy' in s for s in symptoms_lower) else 0
                    
                    self.data.append({
                        "text": user_msg,
                        "labels": [has_sciatica, has_lumbar, has_radiculopathy]
                    })
                except json.JSONDecodeError:
                    pass

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        text = item["text"]
        labels = torch.tensor(item["labels"], dtype=torch.float)
        
        encoding = self.tokenizer(
            text,
            add_special_tokens=True,
            max_length=self.max_length,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt'
        )
        
        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': labels
        }

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    data_path = os.path.join(base_dir, "../dataset/nlpAgent/nlp_finetuning_data.jsonl")
    model_save_dir = os.path.join(base_dir, "../../models/nlp_agent_local")
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")
    
    # 1. Load Model and Tokenizer
    model_name = "distilbert-base-uncased"
    print(f"Loading {model_name}...")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    
    # We are predicting 3 classes: sciatica, lumbar, radiculopathy
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name, 
        num_labels=3,
        problem_type="multi_label_classification"
    )
    model.to(device)

    # 2. Prepare Dataset
    print("Preparing dataset...")
    dataset = JSONLDataset(data_path, tokenizer)
    if len(dataset) == 0:
        print("Dataset is empty. Run `prepare_nlp_dataset.py` first.")
        return
        
    print(f"Loaded {len(dataset)} examples.")
    
    # Simple split (not robust for production, but fine for demo)
    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])
    
    train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=8)

    # 3. Setup Optimizer
    optimizer = AdamW(model.parameters(), lr=2e-5)
    epochs = 3
    total_steps = len(train_loader) * epochs
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)
    loss_fn = torch.nn.BCEWithLogitsLoss()

    # 4. Training Loop
    print("Starting training...")
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        
        for batch in train_loader:
            optimizer.zero_grad()
            
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)
            
            outputs = model(input_ids, attention_mask=attention_mask)
            loss = loss_fn(outputs.logits, labels)
            
            total_loss += loss.item()
            loss.backward()
            
            # Clip gradients to prevent exploding
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            
            optimizer.step()
            scheduler.step()
            
        avg_train_loss = total_loss / len(train_loader)
        
        # Validation
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for batch in val_loader:
                input_ids = batch['input_ids'].to(device)
                attention_mask = batch['attention_mask'].to(device)
                labels = batch['labels'].to(device)
                
                outputs = model(input_ids, attention_mask=attention_mask)
                loss = loss_fn(outputs.logits, labels)
                val_loss += loss.item()
                
        avg_val_loss = (val_loss / len(val_loader)) if len(val_loader) > 0 else 0
        
        print(f"Epoch {epoch+1}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    # 5. Save Model
    print(f"Saving fine-tuned model to {model_save_dir}...")
    os.makedirs(model_save_dir, exist_ok=True)
    model.save_pretrained(model_save_dir)
    tokenizer.save_pretrained(model_save_dir)
    print("Training Complete!")

if __name__ == "__main__":
    main()
